Repository hyperledger/besu, pull requests merged in 2019-09, with the labels that each got.

#46 Store db metadata file in the root data directory.
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
  build.gradle
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuConfiguration.java
  plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
  plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/DatabaseMetadata.java
  plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/helper/Conditions.java
  plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java
  plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/configuration/DatabaseMetadataTest.java
Labels: enhancement

#49 Disallow comments in Genesis JSON file.
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
  config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
Labels: enhancement

#54 Update download link
  README.md
Labels: bug, documentation

#24 [PAN-3023] Add command line option for target gas limit
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
  besu/src/main/java/org/hyperledger/besu/controller/CliqueBesuControllerBuilder.java
  besu/src/main/java/org/hyperledger/besu/controller/GasLimitCalculator.java
  besu/src/main/java/org/hyperledger/besu/controller/IbftBesuControllerBuilder.java
  besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
  besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
  besu/src/test/java/org/hyperledger/besu/RunnerTest.java
  besu/src/test/java/org/hyperledger/besu/chainexport/RlpBlockExporterTest.java
  besu/src/test/java/org/hyperledger/besu/chainimport/JsonBlockImporterTest.java
  besu/src/test/java/org/hyperledger/besu/chainimport/RlpBlockImporterTest.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/java/org/hyperledger/besu/controller/GasLimitCalculatorTest.java
  besu/src/test/resources/everything_config.toml
  consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutor.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractMinerExecutor.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutor.java
  ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutorTest.java
Labels: enhancement

#68 add LGTM badges
  README.md
Labels: documentation

#67 1.3 RC Changelog updates
  CHANGELOG.md
  gradle.properties
Labels: documentation
