Repository hyperledger/besu, pull requests merged in 2020-12, with the labels that each got.

#1642 add sendSignedTransaction method to QuorumEnclave
  enclave/src/integration-test/java/org/hyperledger/besu/enclave/GoQuorumEnclaveTest.java
  enclave/src/main/java/org/hyperledger/besu/enclave/GoQuorumEnclave.java
  enclave/src/main/java/org/hyperledger/besu/enclave/types/GoQuorumSendSignedRequest.java
Labels: TeamRevenant, privacy

#1673 Accept to use default port values if not in use.
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Labels: P3, bug

#1636 Use gasPrice when this field is present (eth_estimateGas)
  CHANGELOG.md
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthCallIntegrationTest.java
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthEstimateGasIntegrationTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/BlockAdapterBase.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCall.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCall.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracer.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/PrivCallTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/CallParameter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParamsTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
Labels: doc-change-required

#1590 Refactored genesis config fork logic.
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
  config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
  config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
  config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
  config/src/test/resources/valid_config.json
  config/src/test/resources/valid_config_with_unexpected_forks.json
Labels: TeamRevenant

#1676 Refactored OrionTestHarness to use in memory storage.
  testutil/src/main/java/org/hyperledger/orion/testutil/OrionConfiguration.java
  testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarness.java
  testutil/src/main/java/org/hyperledger/orion/testutil/OrionTestHarnessFactory.java
Labels: TeamRevenant

#1709 enhanced error message - smart contract permissioning config check
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodePermissioningControllerFactory.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
Labels: TeamRevenant

#1718 Go quorum configuration
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveFactory.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/EnclavePublicKeyProvider.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/GoQuorumPrivacyParameters.java
Labels: TeamRevenant, privacy
