Repository hyperledger/besu, pull requests merged in 2020-11, with the labels that each got.

#1531 Exclude quorum permissioning custom fork in genesis
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
Labels: TeamRevenant

#1510 [1476] Fixed transaction validation bug when local permissioning is enabled
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalConfigPermissioningImportAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningAcceptanceTestBase.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/NodeSmartContractPermissioningV2AcceptanceTestBase.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/TransactionFilter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningController.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerTest.java
Labels: TeamRevenant, permissioning

#1502 Update eth_estimateGas and eth_call RPC APIs for EIP1559 transaction
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonCallParameter.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/CallParameter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
Labels: EIP-1559, doc-change-required

#1542 Handle legacy fork id Eth/64
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/unstable/EthProtocolOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/resources/everything_config.toml
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkId.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ForkIdManager.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdBackwardCompatibilityTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdTestUtil.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/LegacyForkIdManager.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestUtil.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthServerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
Labels: P2, bug

#1554 Added zero gasPrice validation for Quorum compatibility mode.
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
  consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftProtocolSchedule.java
  consensus/ibftlegacy/src/main/java/org/hyperledger/besu/consensus/ibftlegacy/IbftProtocolSchedule.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcErrorConverterTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthSendRawTransactionTest.java
  ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashBlockCreatorTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/difficulty/fixed/FixedDifficultyProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/ExecutionContextTestFixture.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/VMReferenceTest.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
  util/src/test/java/org/hyperledger/besu/util/SubscribersTest.java
Labels: TeamRevenant

#1563 eth_gasPrice based on median block cost (#1546)
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/resources/everything_config.toml
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLDataFetchers.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPrice.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/AbstractEthGraphQLHttpServiceTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPriceTest.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/graphql/eth_gasPrice.json
Labels: doc-change-required

#1575 IBFT2 roundchange not sent if timeout after import
  CHANGELOG.md
  consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/tests/LocalNodeIsProposerTest.java
  consensus/ibft/src/integration-test/java/org/hyperledger/besu/consensus/ibft/tests/LocalNodeNotProposerTest.java
  consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftChainObserver.java
  consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftController.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftChainObserverTest.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/statemachine/IbftControllerTest.java
Labels: TeamGroot

#1599 Go quorum enclave
  enclave/build.gradle
  enclave/src/integration-test/java/org/hyperledger/besu/enclave/GoQuorumEnclaveTest.java
  enclave/src/main/java/org/hyperledger/besu/enclave/Enclave.java
  enclave/src/main/java/org/hyperledger/besu/enclave/EnclaveFactory.java
  enclave/src/main/java/org/hyperledger/besu/enclave/GoQuorumEnclave.java
  enclave/src/main/java/org/hyperledger/besu/enclave/RequestTransmitter.java
  enclave/src/main/java/org/hyperledger/besu/enclave/VertxRequestTransmitter.java
  enclave/src/main/java/org/hyperledger/besu/enclave/types/GoQuorumReceiveResponse.java
  enclave/src/main/java/org/hyperledger/besu/enclave/types/GoQuorumSendRequest.java
Labels: privacy

#1633 Add epochStartBlock function to EpochCalculator interface
  besu/src/main/java/org/hyperledger/besu/controller/MainnetBesuControllerBuilder.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetWork.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetWorkTest.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutor.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMiningCoordinator.java
  ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashBlockCreatorTest.java
  ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/EthHashMinerExecutorTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DirectAcyclicGraphSeed.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EpochCalculator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHash.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHashCacheFactory.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHashSolver.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/EthHasher.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRule.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/EtcHashTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/EthHashSolverTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/EthHashTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRuleTest.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
  ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1EthProxyProtocol.java
  ethereum/stratum/src/main/java/org/hyperledger/besu/ethereum/stratum/Stratum1Protocol.java
  ethereum/stratum/src/test/java/org/hyperledger/besu/ethereum/stratum/StratumConnectionTest.java
Labels: ETC
