Repository hyperledger/besu, pull requests merged in 2020-02, with the labels that each got.

#351 [BESU-176] JRPC response to eth_getTransactionCount is different from other node implementations.
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactions.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionsForSenderInfo.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionsTest.java
Labels: bug, testing

#364 Transaction log indexing - Renamed .index to .cache.
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogsIndexer.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
Labels: enhancement

#395 1.5 RC Changelog
  CHANGELOG.md
Labels: needed-rc

#393 Fixed link
  CHANGELOG.md
Labels: needed-rc

#391 docker changelog
  CHANGELOG.md
Labels: needed-rc

#388 Added known bug to changelog
  CHANGELOG.md
Labels: needed-rc

#367 [BESU-169] cache logs bloom filters automatically.
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  besu/src/main/java/org/hyperledger/besu/Runner.java
  besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/resources/everything_config.toml
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogsIndexingService.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogsIndexer.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/Blockchain.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/ChainReorgObserver.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/TestBlockchain.java
Labels: doc-change-required, enhancement

#407 [PIE-2303] Automatic log bloom caching - Remove usage of pending file.
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/AutoTransactionLogBloomCachingService.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/TransactionLogBloomCacher.java
Labels: enhancement

#409 [PIE-2305] Plugins - Create Plugin Not Found error.
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/PluginsReloadConfiguration.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
Labels: doc-change-required, enhancement
