Repository hyperledger/besu, pull requests merged in 2021-11, with the labels that each got.

#2996 Improved QBFT logs
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/statemachine/BaseBftController.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/statemachine/QbftRound.java
Labels: TeamGroot

#2994 Added validate-config subcommand
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/ValidateConfigSubCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/util/TomlConfigFileDefaultProvider.java
  besu/src/test/java/org/hyperledger/besu/cli/ValidateConfigSubCommandTest.java
Labels: TeamRevenant

#3036 [MINOR] updated comment and added link to generateId code in Tessera
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/privacy/PrivacyGroupUtil.java
Labels: privacy, TeamRevenant

#3057 Feature/keep peers on dns fail
  besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
  ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/NetworkingConfiguration.java
  ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetwork.java
  ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/network/DefaultP2PNetworkTest.java
Labels: documentation

#3087 Rename BftForkSpec to ForkSpec and make it generic
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/ForkSpec.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolSchedule.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BftForksSchedule.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BlockTimer.java
  consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolScheduleTest.java
  consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BftForksScheduleTest.java
  consensus/common/src/test/java/org/hyperledger/besu/consensus/common/bft/BlockTimerTest.java
  consensus/ibft/src/main/java/org/hyperledger/besu/consensus/ibft/IbftForksSchedulesFactory.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftForksSchedulesFactoryTest.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/IbftProtocolScheduleTest.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/blockcreation/BftBlockCreatorTest.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/QbftForksSchedulesFactory.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/blockcreation/QbftBlockCreatorFactory.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ForkingValidatorProvider.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/TransactionValidatorProvider.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorModeTransitionLogger.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/QbftProtocolScheduleTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/blockcreation/QbftBlockCreatorFactoryTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/QbftForksSchedulesFactoryTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorModeTransitionLoggerTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/validator/ValidatorTestUtils.java
Labels: TeamGroot

#3069 Qbft migration protocol schedule
  besu/src/main/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilder.java
  besu/src/test/java/org/hyperledger/besu/controller/ConsensusScheduleBesuControllerBuilderTest.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/CombinedProtocolScheduleFactory.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/ForkSpec.java
  consensus/common/src/test/java/org/hyperledger/besu/consensus/common/CombinedProtocolScheduleFactoryTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MutableProtocolSchedule.java
Labels: TeamGroot
