Repository hyperledger/besu, pull requests merged in 2021-02, with the labels that each got.

#1865 QBFT jsonrpc methods
  besu/src/main/java/org/hyperledger/besu/cli/converter/RpcApisConverter.java
  besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/QbftJsonRpcMethods.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/QbftRpcApis.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftDiscardValidatorVote.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetPendingVotes.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetSignerMetrics.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetValidatorsByBlockHash.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetValidatorsByBlockNumber.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftProposeValidatorVote.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftDiscardValidatorVoteTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetPendingVotesTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetSignerMetricsTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetValidatorsByBlockHashTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetValidatorsByBlockNumberTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftProposeValidatorVoteTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
Labels: TeamGroot

#1872 GoQuorum privacy private receipts
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/MainnetBlockValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/TransactionReceipt.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumBlockProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumKeyValueStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/goquorum/GoQuorumPrivateStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/AbstractBlockProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BodyValidation.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetContractCreationProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/MainnetBlockValidatorTest.java
Labels: TeamRevenant, privacy

#1926 GoQuorum store raw private transaction base64 encoding of payload
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/GoQuorumStoreRawPrivateTransaction.java
Labels: TeamRevenant
