Repository hyperledger/besu, pull requests merged in 2021-08, with the labels that each got.

#2595 Updated transaction validation to check onchain permissions at the transaction pool level
  CHANGELOG.md
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountLocalAndOnChainPermissioningAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/permissioning/AccountSmartContractPermissioningAcceptanceTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParamsTest.java
Labels: TeamRevenant

#2605 removed deprecated privacy-precompiled-address CLI option
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/resources/everything_config.toml
Labels: TeamRevenant

#2609 Fix bug with value transfer
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Labels: TeamRevenant

#2586 Feature/1559 cleanup remove experimentaleip
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/RetestethSubCommand.java
  besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
  besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigFile.java
  config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthGetFilterChangesIntegrationTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthFeeHistoryTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/GenesisState.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/BaseFee.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/EIP1559.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/FeeMarketException.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/LondonFeeMarketException.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/fees/TransactionPriceCalculator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpec.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/FeeMarket.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/LondonFeeMarketBlockHeaderGasPriceValidationRule.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/PoWSolverTest.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPool.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactory.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/NoRewardProtocolScheduleWrapper.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
  ethereum/retesteth/src/test/resources/org/hyperledger/besu/ethereum/retesteth/methods/1559ChainParams.json
Labels: documentation

#2635 Refactoring CmsValidator (internal CRL resolution)
  pki/src/main/java/org/hyperledger/besu/pki/cms/CmsValidator.java
  pki/src/test/java/org/hyperledger/besu/pki/cms/CmsCreationAndValidationTest.java
Labels: dev experience

#2633 Fixed nonce bug in EthGetTransactionCount
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionCount.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionCountTest.java
Labels: bug, testing

#2630 Add native secp256r1 lib
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeConfigurationBuilder.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/crypto/SECP256R1AcceptanceTest.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NativeLibraryOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  crypto/build.gradle
  crypto/src/main/java/org/hyperledger/besu/crypto/SECP256R1.java
  crypto/src/test/java/org/hyperledger/besu/crypto/SECP256R1Test.java
  crypto/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmFactoryTest.java
  gradle/versions.gradle
Labels: enhancement
