Repository hyperledger/besu, pull requests merged in 2021-03, with the labels that each got.

#1669 Add classic fork blocks to admin_nodeInfo
  config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
  config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AdminNodeInfoTest.java
Labels: ETC

#1987 Upgrade to latest ethsigner version to be used in AT
  acceptance-tests/dsl/build.gradle
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/ethsigner/testutil/EthSignerConfig.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/ethsigner/testutil/EthSignerTestHarnessFactory.java
  acceptance-tests/tests/build.gradle
  gradle/versions.gradle
Labels: TeamGroot

#2054 Updated CLI option validation to handle dependent options with multiple main options.
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
Labels: TeamRevenant

#2076 Use istanbul 100 subprotocol in QBFT
  besu/src/main/java/org/hyperledger/besu/controller/QbftBesuControllerBuilder.java
  consensus/qbft/src/main/java/org/hyperledger/besu/consensus/qbft/protocol/Istanbul100SubProtocol.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/protocol/Istanbul100SubProtocolTest.java
Labels: TeamGroot

#2078 Added error handling for GoQuorum genesis file without GoQuorum compatibility enabled
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Labels: TeamRevenant

#2099 Fix flaky test
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/privacy/PrivDebugGetStateRootOnchainGroupAcceptanceTest.java
Labels: flake
