Repository hyperledger/besu, pull requests merged in 2022-06, with the labels that each got.

#3950 Extend block parameter methods to accept 'finalized' and 'safe' as block tags
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterMethod.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/JsonRpcError.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockByNumberTest.java
Labels: doc-change-required, mainnet

#3962 Gray glacier hard fork
  CHANGELOG.md
  besu/src/test/java/org/hyperledger/besu/ForkIdsTest.java
  config/src/main/java/org/hyperledger/besu/config/GenesisConfigOptions.java
  config/src/main/java/org/hyperledger/besu/config/JsonGenesisConfigOptions.java
  config/src/main/java/org/hyperledger/besu/config/StubGenesisConfigOptions.java
  config/src/main/resources/mainnet.json
  config/src/test/java/org/hyperledger/besu/config/GenesisConfigOptionsTest.java
  config/src/test/resources/all_forks.json
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetDifficultyCalculators.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecFactory.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolScheduleBuilder.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/ForkIdTestUtil.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EIP2124Test.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestProtocolSchedules.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/methods/TestSetChainParams.java
Labels: mainnet

#3993 Additional testings on ignored option warning
  besu/src/main/java/org/hyperledger/besu/cli/util/CommandLineUtils.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
Labels: TeamGroot

#4024 Add Sepolia TTD and DNS
  CHANGELOG.md
  config/src/main/resources/sepolia.json
Labels: mainnet

#4027 Return transaction type for legacy transactions
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/TransactionCompleteResult.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getBlockByNumber_complete.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockHashAndIndex_00.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockHashAndIndex_01.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockHashAndIndex_02.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockNumberAndIndex_00.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockNumberAndIndex_01.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockNumberAndIndex_latest.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByBlockNumberAndIndex_pending.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByHash_addressReceiver.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionByHash_contractCreation.json
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/TransactionType.java
Labels: mainnet

#4003 Support free gas networks when using London fee market
  CHANGELOG.md
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarket.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/feemarket/TransactionPriceCalculatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionValidatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/feemarket/LondonFeeMarketTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolTest.java
Labels: doc-change-required

#4032 turns down logging output to debug
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/SyncTargetManager.java
Labels: mainnet

#4019 allow upgrade whether websockets enabled or not
  besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
  besu/src/test/java/org/hyperledger/besu/RunnerBuilderTest.java
Labels: doc-change-required
