Repository hyperledger/besu, pull requests merged in 2023-01, with the labels that each got.

#4869 Remove Deprecated Networks
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/config/NetworkName.java
  besu/src/test/java/org/hyperledger/besu/ForkIdsNetworkConfigTest.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/NetworkDeprecationMessageTest.java
  besu/src/test/java/org/hyperledger/besu/cli/config/EthNetworkConfigTest.java
  besu/src/test/java/org/hyperledger/besu/ethereum/p2p/config/DefaultDiscoveryConfiguration.java
  besu/src/test/java/org/hyperledger/besu/util/LocalPermissioningConfigurationValidatorTest.java
  besu/src/test/resources/permissioning_config_ropsten_bootnodes.toml
  besu/src/test/resources/permissioning_config_sepolia_bootnodes.toml
  config/src/main/resources/astor.json
  config/src/main/resources/calaveras.json
  config/src/main/resources/kiln.json
  config/src/main/resources/ropsten.json
  config/src/main/resources/shandong.json
  config/src/test/java/org/hyperledger/besu/config/GenesisConfigFileTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/forkid/ForkIdTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/forkid/ForkIdTestUtil.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
  ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/mainnet/DifficultyCalculatorTests.java
Labels: doc-change-required

#4888 Peering - disconnect worst peer
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionInvalidReason.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/AbstractRetryingSwitchingPeerTask.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByHashTask.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetHeadersFromPeerByNumberTask.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java
Labels: TeamRevenant, mainnet, peering

#4582 RPC methods that lookup block by hash will now return error if no block found
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAtTest.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getCode_blockHashNotExist.json
Labels: mainnet

#4895 For TimestampSchedule (Shanghai) remove evmBuilder override but leave other mods in
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java
Labels: TeamGroot, mainnet, EIP

#4902 [RPC] add SAFE and FINALIZED options for block param
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractBlockParameterOrBlockHashMethod.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockParameterOrBlockHash.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getTransactionCount_invalidBlockNumber.json
Labels: mainnet, RPC

#4913 Add '--fork=' to EvmTool
  CHANGELOG.md
  config/src/main/resources/experimental.json
  config/src/main/resources/future.json
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/GenesisState.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ScheduleBasedBlockHeaderFunctions.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/CliqueGenesisFileModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommandOptionsModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolComponent.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/GenesisFileModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/IBFTGenesisFileModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/MainnetGenesisFileModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/ProtocolModule.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/QBFTGenesisFileModule.java
Labels: doc-change-required

#4890 Implement engine_forkchoiceUpdated Withdrawals validation
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeMiningCoordinator.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/PayloadAttributes.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/TransitionCoordinator.java
  consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdated.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV1.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineForkchoiceUpdatedV2.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadAttributesParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/ExecutionEngineJsonRpcMethods.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetTransactionReceiptTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineForkchoiceUpdatedTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadAttributesParameterTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTestFixture.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Withdrawal.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpec.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsValidator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/WithdrawalsValidatorTest.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/NoRewardProtocolScheduleWrapper.java
Labels: TeamGroot, mainnet, EIP

#4883 Calculate block value
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeContext.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/PostMergeContext.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionContext.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinator.java
  consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/PostMergeContextTest.java
  consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/blockcreation/MergeCoordinatorTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayload.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV1.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV2.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResultFactory.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayloadTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockValueCalculator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/BlockValueCalculatorTest.java
Labels: mainnet

#4936 [MINOR] Correct order of args to RequestBody.create
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/login/LoginRequestFactory.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceHostWhitelistTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpBySpecTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AdminJsonRpcHttpServiceTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceHostAllowlistTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceLoginTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceParameterizedTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/filter/EthJsonRpcHttpServiceTest.java
Labels: testing, dev experience

#4853 'No sync target' logging improvements
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/util/LogUtil.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncTargetManager.java
Labels: TeamRevenant, logging

#4938 Improve get protocol schedule (only get header and not the entire block)
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
  consensus/merge/src/test/java/org/hyperledger/besu/consensus/merge/TransitionProtocolScheduleTest.java
Labels: mainnet

#4962 Add withdrawals root to block header
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/BlockUtils.java
  besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcResponseKey.java
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcResponseUtils.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineNewPayload.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGasPriceTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineExchangeTransitionConfigurationTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesLogCacheTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/GoQuorumPrivateTxBloomBlockchainQueriesTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/cache/GoQuorumPrivateTransactionLogBloomCacherTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/cache/TransactionLogBloomCacherTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockBody.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeaderBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/SealableBlockHeader.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Withdrawal.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockHeaderTestFixture.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/NonBesuBlockHeader.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/bonsai/LogRollingTests.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/KeccakHasherTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/backwardsync/ChainForTestCreator.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestEnv.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockBody.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockHeader.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/Withdrawal.java
Labels: TeamGroot, mainnet, EIP

#4953 engine_getPayloadV2 Withdrawals
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/BlockReplay.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResultFactory.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/EngineGetPayloadResultV2.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/AbstractEngineGetPayloadTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetPayloadV2Test.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/EnginePayloadAttributesParameterTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/WithdrawalParameterTestFixture.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracerTest.java
Labels: TeamGroot, mainnet, EIP

#4897 use bonsai updater cache to avoid calling database several times for the same account
  CHANGELOG.md
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiPersistedWorldState.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateKeyValueStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai/BonsaiWorldStateUpdater.java
Labels: performance, mainnet

#4957 Updated overview builder to consider networkId and custom network genesis.
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
  besu/src/test/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilderTest.java
Labels: logging

#4942 Add implementation for eth_createAccessList RPC method
  CHANGELOG.md
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthCreateAccessListIntegrationTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessList.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/CreateAccessListResult.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
  evm/src/main/java/org/hyperledger/besu/evm/frame/MessageFrame.java
  evm/src/main/java/org/hyperledger/besu/evm/tracing/AccessListOperationTracer.java
  testutil/src/main/java/org/hyperledger/besu/testutil/BlockTestUtil.java
  testutil/src/main/resources/test-eth-ref-rpc-compact/chain.blocks
  testutil/src/main/resources/test-eth-ref-rpc-compact/genesis.json
Labels: doc-change-required, TeamRevenant, mainnet, RPC

#4973 [MINOR] update some tests from junit 4 to 5
  besu/src/test/java/org/hyperledger/besu/PrivacyReorgTest.java
  besu/src/test/java/org/hyperledger/besu/PrivacyTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpServiceCorsTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceCorsTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/precompiles/privacy/PrivacyPrecompiledContractTest.java
  ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/peers/StaticNodesParserTest.java
Labels: testing

#4860 KZG point eval precompile
  CHANGELOG.md
  build.gradle
  datatypes/src/main/java/org/hyperledger/besu/datatypes/Address.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetPrecompiledContractRegistries.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  evm/build.gradle
  evm/src/main/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompiledContract.java
  evm/src/main/java/org/hyperledger/besu/evm/precompile/MainnetPrecompiledContracts.java
  evm/src/main/resources/org/hyperledger/besu/evm/precompile/mainnet_kzg_trusted_setup_4096.txt
  evm/src/test/java/org/hyperledger/besu/evm/precompile/KZGPointEvalPrecompileContractTest.java
  evm/src/test/resources/org/hyperledger/besu/evm/precompile/fail_pointEvaluation.json
  evm/src/test/resources/org/hyperledger/besu/evm/precompile/trusted_setup_4.txt
  evm/src/test/resources/org/hyperledger/besu/evm/precompile/trusted_setup_4096.txt
  gradle/verification-metadata.xml
  gradle/versions.gradle
Labels: doc-change-required

#4975 [MINOR] move Clique tests to junit5
  consensus/clique/build.gradle
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueBlockChoiceTests.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueBlockHashingTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueBlockInterfaceTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueDifficultyCalculatorTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueExtraDataTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/CliqueProtocolScheduleTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/NodeCanProduceNextBlockTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockCreatorTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueBlockSchedulerTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMinerExecutorTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueMiningCoordinatorTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/blockcreation/CliqueProposerSelectorTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/headervalidationrules/CliqueDifficultyValidationRuleTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/headervalidationrules/CliqueExtraDataValidationRuleTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/headervalidationrules/VoteValidationRuleTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignerMetricsTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignersAtHashTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueGetSignersTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/CliqueProposalsTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/DiscardTest.java
  consensus/clique/src/test/java/org/hyperledger/besu/consensus/clique/jsonrpc/methods/ProposeTest.java
  consensus/common/src/test/java/org/hyperledger/besu/consensus/common/jsonrpc/AbstractVoteProposerMethodTest.java
  consensus/ibft/src/test/java/org/hyperledger/besu/consensus/ibft/jsonrpc/methods/IbftGetPendingVotesTest.java
  consensus/qbft/src/test/java/org/hyperledger/besu/consensus/qbft/jsonrpc/methods/QbftGetPendingVotesTest.java
Labels: testing

#4974 Snap sync logging - concise info and detailed debug log messages
  ethereum/eth/build.gradle
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastImportBlocksStep.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloadPipelineFactory.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncDownloader.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapWorldStateDownloader.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapsyncMetricsManager.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastImportBlocksPercentageCalculationTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastImportBlocksStepTest.java
Labels: mainnet, logging

#4989 split ATs into privacy/permissioning/etc and the rest
  .circleci/config.yml
  acceptance-tests/tests/build.gradle
  container-tests/tests/build.gradle
Labels: testing, dev experience, TeamRevenant

#5000 parallelization for unit tests
  .circleci/config.yml
Labels: testing, dev experience, TeamRevenant

#4999 remove container tests
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/AcceptanceTestBase.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/account/TransferTransaction.java
  container-tests/build.gradle
  container-tests/tests/build.gradle
  container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTestBase.java
  container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/ContainerTests.java
  container-tests/tests/src/test/java/org/hyperledger/besu/tests/container/helpers/ContractOperations.java
  container-tests/tests/src/test/resources/besu/config/besuAddress
  container-tests/tests/src/test/resources/besu/data/key
  container-tests/tests/src/test/resources/genesis.json
  container-tests/tests/src/test/resources/goQuorum/qdata/nodeKey
  container-tests/tests/src/test/resources/ipc/.empty
  container-tests/tests/src/test/resources/keys/key1.key
  container-tests/tests/src/test/resources/keys/key1.pub
  container-tests/tests/src/test/resources/keys/key2.key
  container-tests/tests/src/test/resources/keys/key2.pub
  container-tests/tests/src/test/resources/tessera/tesseraConfig.json
  container-tests/tests/src/test/solidity/TestContract.sol
  settings.gradle
Labels: testing, dev experience, TeamRevenant

#5011 DebugGetRawBlock and DebugGetRawHeader missing methods
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugGetRawBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugGetRawHeader.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugJsonRpcMethods.java
Labels: doc-change-required, TeamRevenant
