Repository hyperledger/besu, pull requests merged in 2023-12, with the labels that each got.

#6185 Add RockDB Subcommand for printing usage per column family
  CHANGELOG.md
  besu/build.gradle
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbSubCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbUsageHelper.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommand.java
  crypto/algorithms/src/main/java/org/hyperledger/besu/crypto/KeyPairUtil.java
Labels: TeamGroot

#6230 Deprecation warning if Forest pruning is enabled
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Labels: doc-change-required

#6234 crypto migrate to junit 5
  crypto/algorithms/build.gradle
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/ECPointUtilTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/HashTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/KeyPairTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/KeyPairUtilTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECP256K1Test.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECP256R1Test.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECPPrivateKeyTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECPPublicKeyTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SECPSignatureTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmFactoryTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/SignatureAlgorithmTypeTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/AltBn128Fq12PairerTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/AltBn128Fq12PointTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/AltBn128Fq2PointTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/AltBn128PointTest.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/Fq12Test.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/Fq2Test.java
  crypto/algorithms/src/test/java/org/hyperledger/besu/crypto/altbn128/FqTest.java
Labels: testing

#6254 [MINOR] fix log params for Failed to retrieve chain head
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/ChainHeadTracker.java
Labels: logging

#6255 add extra gradle task dependency to silence warning
  acceptance-tests/tests/build.gradle
Labels: dev experience

#6273 log bootnodes and static nodes list at debug level
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Labels: logging

#6256 plugin and jsonrpc ATs to junit 5
  acceptance-tests/test-plugins/build.gradle
  acceptance-tests/test-plugins/src/test/java/org/hyperledger/besu/services/BesuPluginContextImplTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/AbstractJsonRpcTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DebugReplayBlockAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/DebugSetHeadAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthGetBlockByNumberAndHashShanghaiAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineCancunBlockBuildingAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineEip6110AcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineParisAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ExecutionEngineShanghaiAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/ipc/Web3JSupportAcceptanceTest.java
Labels: testing

#6260 Non bft group ats junit 5
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/AbstractPreexistingNodeTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/LoggingTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/backup/BackupRoundTripAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterNoDiscoveryAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/ClusterThreadNodeRunnerAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/P2pDisabledAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/bootstrap/StaticNodesAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/config/BootNodesGenesisSetupTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/crypto/SECP256R1AcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/database/DatabaseMigrationAcceptanceTest.java
Labels: testing

#6296 [MINOR] Remove vintage engine dependencies where unused
  consensus/clique/build.gradle
  consensus/common/build.gradle
  crypto/algorithms/build.gradle
  datatypes/build.gradle
  errorprone-checks/build.gradle
  ethereum/evmtool/build.gradle
  evm/build.gradle
  nat/build.gradle
  pki/build.gradle
  util/build.gradle
Labels: testing

#6281 [MINOR] CLI unit tests migrate to junit 5
  besu/src/test/java/org/hyperledger/besu/chainexport/RlpBlockExporterTest.java
  besu/src/test/java/org/hyperledger/besu/chainimport/JsonBlockImporterTest.java
  besu/src/test/java/org/hyperledger/besu/cli/config/EthNetworkConfigTest.java
  besu/src/test/java/org/hyperledger/besu/cli/converter/FractionConverterTest.java
  besu/src/test/java/org/hyperledger/besu/cli/converter/MetricCategoryConverterTest.java
  besu/src/test/java/org/hyperledger/besu/cli/converter/PercentageConverterTest.java
  besu/src/test/java/org/hyperledger/besu/cli/custom/RpcAuthFileValidatorTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/OptionParserTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/stable/LoggingLevelOptionTest.java
  besu/src/test/java/org/hyperledger/besu/cli/util/BesuCommandCustomFactoryTest.java
  besu/src/test/java/org/hyperledger/besu/cli/util/VersionProviderTest.java
Labels: testing, TeamRevenant

#6282 [MINOR] CLI Subcommands migrate to junit 5
  besu/build.gradle
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/ValidateConfigSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/operator/OperatorSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/AbstractCLIOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/EthProtocolOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/MetricsCLIOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/MiningOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/SynchronizerOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/options/stable/DataStorageOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/rlp/RLPSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommandTest.java
Labels: testing, TeamRevenant

#6297 [MINOR] add genesis file name to config overview
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
  besu/src/test/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilderTest.java
Labels: logging, ux, non mainnet (private networks)

#6283 [MINOR] More cli tests to junit 5
  besu/src/test/java/org/hyperledger/besu/cli/CommandLineUtilsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/EnvironmentVariableDefaultProviderTest.java
  besu/src/test/java/org/hyperledger/besu/cli/TomlConfigFileDefaultProviderTest.java
  besu/src/test/java/org/hyperledger/besu/cli/util/ConfigOptionSearchAndRunHandlerTest.java
  besu/src/test/java/org/hyperledger/besu/services/BesuEventsImplTest.java
  besu/src/test/java/org/hyperledger/besu/services/PicoCLIOptionsImplTest.java
Labels: testing, TeamRevenant

#6299 [MINOR] Trailing peer limit log
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/TrailingPeerLimiter.java
Labels: TeamRevenant, logging
