Repository hyperledger/besu, pull requests merged in 2024-02, with the labels that each got.

#6483 Report estimated disk space freed up by x-trie-log prune subcommand
  besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbHelper.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbSubCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelper.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogHelperTest.java
Labels: TeamGroot

#6501 Deprecate --Xp2p-peer-lower-bound
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
  besu/src/main/java/org/hyperledger/besu/cli/options/unstable/NetworkingOptions.java
  besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
  besu/src/test/java/org/hyperledger/besu/RunnerTest.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/java/org/hyperledger/besu/cli/options/NetworkingOptionsTest.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestUtil.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/ethtaskutils/AbstractMessageTaskTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/AbstractBlockPropagationManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TestNode.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolFactoryTest.java
  ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/config/NetworkingConfiguration.java
  ethereum/retesteth/src/main/java/org/hyperledger/besu/ethereum/retesteth/RetestethContext.java
Labels: doc-change-required

#6526 Acceptance Tests - only run non-privacy ATs
  .github/workflows/acceptance-tests.yml
  acceptance-tests/tests/build.gradle
Labels: testing

#6522 increase timeout for websocket pub/sub tests
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/pubsub/WebSocket.java
Labels: testing, flake

#6534 [minor] Improve message when existing database is different from the configuration
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageFormat.java
  plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
  plugins/rocksdb/src/test/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactoryTest.java
Labels: ux

#6505 Code storage by hash v2
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/options/stable/DataStorageOptionsTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/BonsaiSnapshotWorldStateKeyValueStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/BonsaiWorldStateKeyValueStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/AccountHashCodeStorageStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/CodeHashCodeStorageStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/CodeStorageStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/FlatDbStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/FlatDbStrategyProvider.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/FullFlatDbStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/PartialFlatDbStrategy.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldState.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/forest/storage/ForestWorldStateKeyValueStorage.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/WorldStateStorage.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/BonsaiWorldStateKeyValueStorageTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/bonsai/storage/flat/FlatDbStrategyProviderTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/bonsai/worldview/BonsaiWorldStateTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/forest/storage/ForestKeyValueStorageWorldStateStorageTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/PersistDataStepTest.java
Labels: TeamGroot

#6551 use terminal width for usage message
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Labels: ux

#6568 Add tests for user profiles
  besu/src/test/java/org/hyperledger/besu/cli/CascadingDefaultProviderTest.java
  besu/src/test/java/org/hyperledger/besu/cli/ProfilesTest.java
  config/src/main/resources/profiles/minimalist-staker.toml
Labels: testing

#6540 rocksdb usage - Replace Column Size with more accurate Total Size
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbHelper.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/RocksDbSubCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/StorageSubCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/subcommands/storage/TrieLogSubCommand.java
Labels: TeamGroot

#6581 feat: add `eth_blobBaseFee`
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/RpcMethod.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthBlobBaseFee.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthBlobBaseFeeTest.java
Labels: doc-change-required, mainnet

#6536 Default storage format now Bonsai
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  besu/src/main/java/org/hyperledger/besu/cli/options/stable/DataStorageOptions.java
  besu/src/test/java/org/hyperledger/besu/RunnerTest.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/controller/BesuControllerBuilderTest.java
  besu/src/test/java/org/hyperledger/besu/controller/MergeBesuControllerBuilderTest.java
  besu/src/test/java/org/hyperledger/besu/controller/QbftBesuControllerBuilderTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/InMemoryKeyValueStorageProvider.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/GenesisStateTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/PersistDataStepTest.java
Labels: doc-change-required

#6625 prevent startup if PoA and snap/checkpoint
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
Labels: doc-change-required
