Repository hyperledger/besu, pull requests merged in 2024-12, with the labels that each got.

#7962 Fix verkle pipeline
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/BlockHeader.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/VerkleDevnetBlockHeaderFunctions.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/BlockchainTestSubCommand.java
  ethereum/referencetests/build.gradle
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCase.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpec.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/CandidateBlock.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/VerkleReferenceTestCaseSpec.java
  ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/referencetests/BlockchainReferenceTestCaseSpecTest.java
  ethereum/referencetests/src/reference-test/java/org/hyperledger/besu/ethereum/vm/BlockchainReferenceTestTools.java
  evm/src/main/java/org/hyperledger/besu/evm/fluent/EVMExecutor.java
  evm/src/test/java/org/hyperledger/besu/evm/fluent/EVMExecutorTest.java
  evm/src/test/java/org/hyperledger/besu/evm/operation/PushOperationTest.java
Labels: verkle

#7957 add tests on pull request for verkle branch
  .github/workflows/acceptance-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pre-review.yml
  .github/workflows/reference-tests.yml
Labels: verkle

#7758 update trace logique to fix journal updater issue
  besu/src/main/java/org/hyperledger/besu/services/TraceServiceImpl.java
Labels: Stale

#7965 Allow frontier simulation when Base Fee is present
  CHANGELOG.md
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/london/EthEstimateGasIntegrationTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
Labels: bug, mainnet

#6646 Retrieve all transaction receipts for a block in one request
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/NormalBlockAdapter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/PendingStateAdapter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetBlockReceipts.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetMinerDataByBlockHash.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueries.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/query/BlockchainQueriesTest.java
Labels: Stale

#7978 Add RPC HTTP options to specify custom truststore and password
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/JsonRpcHttpOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/options/JsonRpcHttpOptionsTest.java
  besu/src/test/resources/everything_config.toml
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpService.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/tls/TlsClientAuthConfiguration.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTlsClientAuthTest.java
Labels: doc-change-required

#7941 eth_simulateV1 - Add BlockSimulator feature
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/services/BlockSimulatorServiceImpl.java
  besu/src/main/java/org/hyperledger/besu/services/BlockchainServiceImpl.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockOverridesParameter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/CallProcessingResult.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpServiceTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulationException.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulationResult.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockStateCall.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorResult.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/BlockSimulatorTest.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockOverrides.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/PluginBlockSimulationResult.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BlockSimulationService.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BlockchainService.java
Labels: mainnet, RPC, linea
