Repository hyperledger/besu, pull requests merged in 2025-07, with the labels that each got.

#8926 chore: update blob base cost
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/OsakaTargetingGasLimitCalculator.java
Labels: Osaka

#8925 chore: double P256VERIFY cost
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/FrontierGasCalculator.java
  evm/src/test/java/org/hyperledger/besu/evm/precompile/P256VerifyPrecompiledContractTest.java
Labels: Osaka

#8924 feat: getBlobsV2 devnet 3 changes
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV1.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV2.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/response/RpcErrorType.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV1Test.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/engine/EngineGetBlobsV2Test.java
Labels: Osaka

#8771 feat: EIP-7939 Implement counting leading zero operation
  ethereum/core/src/jmh/java/org/hyperledger/besu/ethereum/vm/operations/OneMillionCountLeadingZerosOperationBenchmark.java
  ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/clz-opcode.json
  evm/src/main/java/org/hyperledger/besu/evm/EVM.java
  evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
  evm/src/main/java/org/hyperledger/besu/evm/operation/CountLeadingZerosOperation.java
  evm/src/test/java/org/hyperledger/besu/evm/operation/CountLeadingZerosOperationTest.java
Labels: Osaka

#8922 Triple the general price of ModExp to reflect the last change in EIP-7883
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
Labels: Osaka

#8941 remove privacy benchmarking config - caliper
  benchmark/caliper-benchmarks/.keep
  benchmark/config/besu-keystore/key
  benchmark/config/caliper-benchconfig-offchain.yaml
  benchmark/config/caliper-benchconfig-onchain.yaml
  benchmark/config/caliper-networkconfig-offchain.json
  benchmark/config/caliper-networkconfig-onchain.json
  benchmark/config/caliper-offchain.yaml
  benchmark/config/caliper-onchain.yaml
  benchmark/config/genesis.json
  benchmark/config/storage.json
  benchmark/config/store.js
  benchmark/config/tessera/config.json
  benchmark/docker-compose.yml
Labels: privacy, techdebt

#8947 refresh the mainnet.json used for blockchain util tests
  testutil/src/main/resources/mainnet-data/mainnet.json
Labels: testing

#8946 added getLast and forkId to eth_config
  CHANGELOG.md
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/TransitionProtocolSchedule.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthConfig.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/EthJsonRpcMethods.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactory.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceHostAllowlistTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceLoginTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTestBase.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTlsClientAuthTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTlsMisconfigurationTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceTlsTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/bonsai/EthConfigBySpecTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/JsonRpcMethodsFactoryTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/websocket/WebSocketServiceLoginTest.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/config/chain-data/mainnet-plus-future.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/config/eth_config.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_config.json
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/forkid/ForkId.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/forkid/ForkIdManager.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/DefaultProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSchedule.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/DefaultProtocolScheduleTest.java
Labels: Osaka

#8952 feat: Wiring framework for tracer config options in debug_trace* methods
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/DebugTraceTransactionIntegrationTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractDebugTraceBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceByBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceByHash.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceCall.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAt.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByNumber.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceCall.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransaction.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionStep.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionStepFactory.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceCallMany.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceRawTransaction.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceReplayBlockTransactions.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TransactionTraceParams.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracer.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/DebugTraceTransactionResult.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/OpCodeLoggerTracerResult.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByHashTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockByNumberTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceBlockTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionStepFactoryTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionTest.java
  ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/vm/TraceTransactionIntegrationTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/OpCodeTracerConfig.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TraceOptions.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TracerType.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracerTest.java
Labels: RPC

#8974 remove fast sync from genesis tests from RunnerTest
  app/src/test/java/org/hyperledger/besu/RunnerTest.java
Labels: testing, flake

#8962 [GHA] remove separate QBFT AT task
  .github/workflows/acceptance-qbft-tests.yml
  acceptance-tests/tests/build.gradle
Labels: testing, techdebt

#8819 refactor: central control point for genesis used in tests
  app/src/test/java/org/hyperledger/besu/services/RlpConverterServiceImplTest.java
  consensus/qbft-core/src/integration-test/java/org/hyperledger/besu/consensus/qbft/core/support/TestContextBuilder.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcHttpServiceRpcApisTest.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/ProtocolScheduleFixture.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/GenesisStateTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolScheduleTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/headervalidationrules/ProofOfWorkValidationRuleTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTestBuilder.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/NewBlockMessageTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/DaoForkPeerValidatorTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/peervalidation/RequiredBlocksPeerValidatorTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/DownloadReceiptsStepTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActionsTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/worldstate/FastWorldStateDownloaderTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/FullSyncTargetManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/AbstractDetermineCommonAncestorTaskParameterizedTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/tasks/DetermineCommonAncestorTaskTest.java
Labels: techdebt

#8987 Generate distribution dependencies catalog
  CHANGELOG.md
  app/build.gradle
  build.gradle
Labels: dev experience, plugins

#8877 Enable decoding for large RPC requests
  CHANGELOG.md
  app/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  app/src/main/java/org/hyperledger/besu/cli/DefaultCommandValues.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/EngineJsonRpcService.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcConfiguration.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/JsonRpcParameter.java
Labels: performance

#8885 Eliminate AbstractRLPInput abstraction to reduce technical debt
  ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/AbstractRLPInput.java
  ethereum/rlp/src/main/java/org/hyperledger/besu/ethereum/rlp/BytesValueRLPInput.java
Labels: Stale

#9024 Add WorldStateService to the plugin API
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ThreadBesuNodeRunner.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
  acceptance-tests/test-plugins/build.gradle
  acceptance-tests/test-plugins/src/main/java/org/hyperledger/besu/tests/acceptance/plugins/TestWorldStateServicePlugin.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/plugins/WorldStateServicePluginTest.java
  app/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  app/src/main/java/org/hyperledger/besu/services/WorldStateServiceImpl.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/WorldStateService.java
Labels: enhancement, plugins
