Repository hyperledger/besu, pull requests merged in 2025-03, with the labels that each got.

#8374 disable flaky test
  ethereum/p2p/src/test/java/org/hyperledger/besu/ethereum/p2p/discovery/dns/DNSDaemonTest.java
Labels: flake

#8375 eth_simulateV1 - Fill gaps between block calls
  besu/src/main/java/org/hyperledger/besu/services/BlockSimulatorServiceImpl.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulationParameter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockStateCall.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockStateCalls.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/BlockSimulatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/BlockStateCallsTest.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockOverrides.java
Labels: RPC

#8127 Plugin API - add methods returning actual RPC host/port values
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/diffbased/bonsai/AbstractIsolationTests.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/BesuConfiguration.java
Labels: plugins

#8419 Add requests hash to block result
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/BlockResult.java
Labels: mainnet, RPC, Prague

#8447 Block Import: move worldstate head only if import successful
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockImporter.java
Labels: bonsai

#8461 update to tuweni 2.7.0 and discovery 25.3.0
  CHANGELOG.md
  acceptance-tests/dsl/build.gradle
  acceptance-tests/tests/build.gradle
  besu/build.gradle
  config/build.gradle
  consensus/clique/build.gradle
  consensus/common/build.gradle
  consensus/ibft/build.gradle
  consensus/merge/build.gradle
  consensus/qbft-core/build.gradle
  consensus/qbft/build.gradle
  crypto/algorithms/build.gradle
  datatypes/build.gradle
  enclave/build.gradle
  ethereum/api/build.gradle
  ethereum/blockcreation/build.gradle
  ethereum/core/build.gradle
  ethereum/eth/build.gradle
  ethereum/ethstats/build.gradle
  ethereum/mock-p2p/build.gradle
  ethereum/p2p/build.gradle
  ethereum/permissioning/build.gradle
  ethereum/referencetests/build.gradle
  ethereum/rlp/build.gradle
  ethereum/stratum/build.gradle
  ethereum/trie/build.gradle
  ethereum/verkletrie/build.gradle
  evm/build.gradle
  gradle/verification-metadata.xml
  platform/build.gradle
  plugin-api/build.gradle
  plugins/rocksdb/build.gradle
  privacy-contracts/build.gradle
  services/tasks/build.gradle
  testfuzz/build.gradle
  testutil/build.gradle
Labels: dependencies

#8390 eth_simulateV1 - Refactoring of Block Simulator
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/BlockOverridesParameter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/LogWithMetadata.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockCallSimulationResult.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulationException.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulationResult.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/exceptions/BlockStateCallException.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/BlockSimulatorTest.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/data/BlockOverrides.java
Labels: mainnet, RPC

#8463 minor changes to RPC result formatting
  evm/src/main/java/org/hyperledger/besu/evm/tracing/AccessListOperationTracer.java
Labels: testing, RPC, hive

#8434 Bonsai - check for null before clearing storage
  CHANGELOG.md
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/worldview/BonsaiWorldState.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/trie/pathbased/common/worldview/accumulator/PathBasedWorldStateUpdateAccumulator.java
Labels: bonsai, hive

#8472 estimate gas - don't override gasPrice if not set
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
Labels: RPC, hive
