Repository hyperledger/besu, pull requests merged in 2025-05, with the labels that each got.

#8510 Add support for grafana-pyroscope to besu
  CHANGELOG.md
  docker/Dockerfile
Labels: doc-change-required

#8299 Remove deprecated `MetricsSystem::createLabelledGauge`
  CHANGELOG.md
  metrics/core/src/main/java/org/hyperledger/besu/metrics/noop/NoOpMetricsSystem.java
  metrics/core/src/main/java/org/hyperledger/besu/metrics/opentelemetry/OpenTelemetryGauge.java
  metrics/core/src/main/java/org/hyperledger/besu/metrics/prometheus/PrometheusSuppliedGauge.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/MetricsSystem.java
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/metrics/LabelledGauge.java
Labels: breaking

#8614 Remove the deprecated `--tx-pool-disable-locals` option
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/TransactionPoolOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/options/TransactionPoolOptionsTest.java
Labels: doc-change-required, breaking

#8595 remove smart contract perm tests
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/permissioning/PermissionedNodeBuilder.java
  besu/src/test/java/org/hyperledger/besu/cli/options/PermissionsOptionsTest.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactoryTest.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
Labels: testing, permissioning

#8336 Add witness tracing
  besu/src/main/java/org/hyperledger/besu/chainimport/JsonBlockImporter.java
  datatypes/src/main/java/org/hyperledger/besu/datatypes/AccessEvent.java
  ethereum/api/build.gradle
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceByBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractTraceByHash.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugAccountAt.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceBlock.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceFilter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/TraceReplayBlockTransactions.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/parameters/TransactionTraceParams.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/privacy/methods/priv/AbstractPrivateTraceByHash.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/processor/TransactionTracer.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLog.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/AbstractJsonRpcHttpServiceTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugTraceTransactionTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/results/StructLogTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/verkle/DebugTraceJsonRpcHttpBySpecTest.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-call/debug_traceCall_all.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-call/debug_traceCall_disableMemory.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-call/debug_traceCall_disableStack.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-call/debug_traceCall_disableStorage.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-call/debug_traceCall_noGasPrice.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-transaction/debug_traceTransaction_default.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-transaction/debug_traceTransaction_disableMemory.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-transaction/debug_traceTransaction_disableStack.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/trace-transaction/debug_traceTransaction_disableStorage.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/verkle/trace-block/debug_traceBlock_enableStatelessWitness.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/verkle/trace-call/debug_traceCall_enableStatelessAccessWitness.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/debug/verkle/trace-transaction/debug_traceTransaction_enableStatelessAccessWitness.json
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/trace/chain-data/genesis-verkle.json
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/AbstractBlockCreator.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockCreator.java
  ethereum/blockcreation/src/main/java/org/hyperledger/besu/ethereum/blockcreation/BlockMiner.java
  ethereum/core/src/integration-test/java/org/hyperledger/besu/ethereum/vm/TraceTransactionIntegrationTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TraceFrame.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/debug/TraceOptions.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/BlockImportResult.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockImporter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracer.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/BlockchainSetupUtil.java
  ethereum/core/src/test-support/java/org/hyperledger/besu/ethereum/core/MessageFrameTestFixture.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/DefaultProtocolScheduleTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/trie/pathbased/bonsai/AbstractIsolationTests.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/DebugOperationTracerTest.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/EvmToolCommand.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/StateTestSubCommand.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nServerSubCommand.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/T8nSubCommand.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/BranchAccessEvent.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/LeafAccessEvent.java
  evm/src/main/java/org/hyperledger/besu/evm/tracing/StandardJsonTracer.java
  evm/src/test/java/org/hyperledger/besu/evm/StandardJsonTracerTest.java
  evm/src/test/java/org/hyperledger/besu/evm/fluent/EVMExecutorTest.java
  evm/src/test/java/org/hyperledger/besu/evm/toy/EvmToyCommand.java
Labels: stateless

#8643 update ref tests to 4.5.0
  ethereum/referencetests/build.gradle
  gradle/verification-metadata.xml
Labels: testing, Osaka

#8627 Estimate gas on pending block by default
  CHANGELOG.md
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/JsonRpcTestMethodsFactory.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
Labels: doc-change-required

#8658 refactor: add blob schedule to protocol spec builder
  config/src/main/java/org/hyperledger/besu/config/BlobSchedule.java
  config/src/main/java/org/hyperledger/besu/config/BlobScheduleOptions.java
  consensus/clique/src/main/java/org/hyperledger/besu/consensus/clique/CliqueProtocolSchedule.java
  consensus/common/src/main/java/org/hyperledger/besu/consensus/common/bft/BaseBftProtocolScheduleBuilder.java
  consensus/ibftlegacy/src/main/java/org/hyperledger/besu/consensus/ibftlegacy/IbftProtocolSchedule.java
  consensus/merge/src/main/java/org/hyperledger/besu/consensus/merge/MergeProtocolSchedule.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ClassicProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetBlockHeaderValidator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecs.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/ProtocolSpecBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/CancunFeeMarket.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/feemarket/PragueFeeMarket.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/MainnetProtocolSpecsTest.java
Labels: Osaka

#8662 unstable options help - ensure no duplicates
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/UnstableOptionsSubCommand.java
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
Labels: ux

#8663 [fusaka-devnet-0] fusaka devnet 0 refTests
  build.gradle
  ethereum/referencetests/build.gradle
  gradle/verification-metadata.xml
Labels: Osaka

#8665 [fusaka-devnet-0] trigger workflows on fusaka branch
  .github/workflows/acceptance-tests.yml
  .github/workflows/integration-tests.yml
  .github/workflows/pre-review.yml
  .github/workflows/reference-tests.yml
Labels: Osaka

#8667 [fusaka-devnet-0] EIP-7883, modexp gas calculation for Osaka
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/ByzantiumGasCalculator.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
  evm/src/test/java/org/hyperledger/besu/evm/precompile/Benchmarks.java
Labels: Osaka

#8655 remove PrivacyOptionsTest
  besu/src/test/java/org/hyperledger/besu/cli/PrivacyOptionsTest.java
  besu/src/test/resources/orion_publickey.pub
Labels: testing

#8666 CLI options tests - check error first; fix typo rpl
  besu/src/test/java/org/hyperledger/besu/cli/BesuCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/NatOptionsTest.java
  besu/src/test/java/org/hyperledger/besu/cli/PasswordSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/PublicKeySubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/ValidateConfigSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/blocks/BlocksSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/operator/OperatorSubCommandTest.java
  besu/src/test/java/org/hyperledger/besu/cli/subcommands/rlp/RLPSubCommandTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/Transaction.java
Labels: testing

#8611 Disable transaction indexing during initial sync by default
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/SynchronizerOptions.java
  besu/src/test/resources/everything_config.toml
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/snapsync/SnapSyncConfiguration.java
Labels: doc-change-required, syncing

#8519 feat: implement EIP-7642 eth/69 subprotocol
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/condition/net/AwaitNetPeerCount.java
  besu/src/main/java/org/hyperledger/besu/chainimport/Era1BlockImporter.java
  besu/src/main/java/org/hyperledger/besu/services/RlpConverterServiceImpl.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/internal/pojoadapter/TransactionAdapter.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/DebugGetRawReceipts.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/Blockchain.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchain.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/TransactionReceiptDecoder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/TransactionReceiptEncoder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/encoding/receipt/TransactionReceiptEncodingConfiguration.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/storage/keyvalue/KeyValueStoragePrefixedKeyBlockchainStorage.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/DefaultBlockchainTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionReceiptEncodingConfigurationTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/TransactionReceiptTest.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocol.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolConfiguration.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/EthProtocolVersion.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/ChainState.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthMessages.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeer.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthPeers.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManager.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/EthServer.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/MergePeerFilter.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapProtocolManager.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/snap/SnapServer.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/manager/task/GetReceiptsFromPeerTask.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/BlockRangeUpdateMessage.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/EthProtocolMessages.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/ReceiptsMessage.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/messages/StatusMessage.java
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockRangeBroadcaster.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthPeersTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthProtocolManagerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/EthServerTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/RespondingEthPeer.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/manager/peertask/task/GetReceiptsFromPeerTaskTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/BlockRangeUpdateMessageTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/MessageWrapperTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/ReceiptsMessageTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/messages/StatusMessageTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/BlockRangeBroadcasterTest.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fullsync/BetterSyncTargetEvaluatorTest.java
  ethereum/evmtool/src/main/java/org/hyperledger/besu/evmtool/t8n/T8nBlockchain.java
  ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/connections/netty/DeFramer.java
  ethereum/p2p/src/main/java/org/hyperledger/besu/ethereum/p2p/rlpx/wire/messages/DisconnectMessage.java
  ethereum/referencetests/src/main/java/org/hyperledger/besu/ethereum/referencetests/ReferenceTestBlockchain.java
Labels: mainnet, history

#8675 Add `--Xhistory-expiry-prune` for enabling optimal RocksDB GC settings
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/ConfigurationOverviewBuilder.java
  besu/src/main/java/org/hyperledger/besu/cli/options/storage/DataStorageOptions.java
  besu/src/main/java/org/hyperledger/besu/services/BesuConfigurationImpl.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/worldstate/DataStorageConfiguration.java
  plugin-api/build.gradle
  plugin-api/src/main/java/org/hyperledger/besu/plugin/services/storage/DataStorageConfiguration.java
  plugins/rocksdb/src/main/java/org/hyperledger/besu/plugin/services/storage/rocksdb/RocksDBKeyValueStorageFactory.java
Labels: history

#8629 Make gas estimation strict by default
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/CallSmartContractFunction.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/DeploySmartContractTransaction.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/transaction/contract/ContractTransactions.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/jsonrpc/EthEstimateGasZeroToleranceAcceptanceTest.java
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptanceqbft/jsonrpc/EthEstimateGasAcceptanceTest.java
  ethereum/api/src/integration-test/java/org/hyperledger/besu/ethereum/api/jsonrpc/methods/fork/frontier/EthEstimateGasIntegrationTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/AbstractEstimateGas.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessList.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGas.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCreateAccessListTest.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthEstimateGasTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/MainnetTransactionProcessor.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/TransactionValidationParams.java
Labels: doc-change-required

#8597 remove smart contract permissioning config options
  CHANGELOG.md
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/ProcessBesuNodeRunner.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/BesuNodeFactory.java
  acceptance-tests/dsl/src/main/java/org/hyperledger/besu/tests/acceptance/dsl/node/configuration/permissioning/PermissionedNodeBuilder.java
  besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
  besu/src/main/java/org/hyperledger/besu/cli/options/PermissionsOptions.java
  besu/src/test/resources/everything_config.toml
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/PermissionTransactionFilter.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/PermissionTransactionValidator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/mainnet/PermissionTransactionValidatorTest.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/AbstractNodeSmartContractPermissioningController.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodePermissioningControllerFactory.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractPermissioningController.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/NodeSmartContractV2PermissioningController.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/PermissioningConfiguration.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/PermissioningConfigurationBuilder.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/SmartContractPermissioningConfiguration.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningController.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactory.java
  ethereum/permissioning/src/main/java/org/hyperledger/besu/ethereum/permissioning/node/provider/SyncStatusNodePermissioningProvider.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerFactoryTest.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/account/AccountPermissioningControllerTest.java
  ethereum/permissioning/src/test/java/org/hyperledger/besu/ethereum/permissioning/node/NodePermissioningControllerFactoryTest.java
Labels: breaking, permissioning

#8695 chore: increase the default for blob prioritized transactions
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/TransactionPoolConfiguration.java
Labels: Osaka

#8416 Chore:Remove deprecated CLI --Xsnapsync-synchronizer-flat-db-healing-…
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/storage/PathBasedExtraStorageOptions.java
Labels: breaking

#8707 EIP-7883 modexp gas calculation changes for Osaka
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/ByzantiumGasCalculator.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
  evm/src/test/java/org/hyperledger/besu/evm/precompile/Benchmarks.java
Labels: Osaka

#8714 fix(eth/69): validate block range message
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/sync/BlockRangeBroadcaster.java
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/BlockRangeBroadcasterTest.java
Labels: history, hive

#8506 8337 modify chain data pruner
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/options/ChainPruningOptions.java
  besu/src/main/java/org/hyperledger/besu/controller/BesuControllerBuilder.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/ChainDataPruner.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/chain/ChainPrunerConfiguration.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/chain/ChainDataPrunerTest.java
  util/src/main/java/org/hyperledger/besu/util/log/LogUtil.java
Labels: history
