Repository hyperledger/besu, pull requests merged in 2025-02, with the labels that each got.

#8166 Simulation: Add `state` to StateOverride (eth_call, eth_simulateV1).
  datatypes/src/main/java/org/hyperledger/besu/datatypes/StateOverride.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthCallTest.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/BlockSimulator.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulator.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/BlockSimulatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/util/StateOverrideParameterTest.java
Labels: doc-change-required

#8212 EIP-7702 Skip CodeDelegation processing for invalid recid
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/core/CodeDelegation.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/mainnet/CodeDelegationProcessor.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/core/CodeDelegationTest.java
Labels: Prague

#8239 disable flaky test classes
  acceptance-tests/tests/src/test/java/org/hyperledger/besu/tests/acceptance/clique/CliqueProposeRpcAcceptanceTest.java
  ethereum/blockcreation/src/test/java/org/hyperledger/besu/ethereum/blockcreation/LegacyFeeMarketBlockTransactionSelectorTest.java
Labels: testing, flake

#8222 Use 9 for max blobs when sizing BlobCache
  ethereum/eth/src/main/java/org/hyperledger/besu/ethereum/eth/transactions/BlobCache.java
Labels: Prague

#8208 [TESTING] disable flaky fast sync actions test
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/sync/fastsync/FastSyncActionsTest.java
Labels: testing, flake

#8251 update rpc gas cap default to 50M
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/ApiConfigurationOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/options/ApiConfigurationOptionsTest.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/transaction/TransactionSimulatorTest.java
Labels: doc-change-required

#7910 Add TLS/mTLS options and configure the GraphQL HTTP service
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/cli/options/GraphQlOptions.java
  besu/src/test/resources/everything_config.toml
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLConfiguration.java
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpService.java
  ethereum/api/src/test/java/org/hyperledger/besu/ethereum/api/graphql/GraphQLHttpsServiceTest.java
Labels: doc-change-required

#8290 RPC - eth_getLogs: Return block not found instead of empty logs
  CHANGELOG.md
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/jsonrpc/internal/methods/EthGetLogs.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/eth_getLogs_blockhash_missingBlockHash.json
Labels: RPC

#8289 remove k8s NAT method
  CHANGELOG.md
  besu/src/main/java/org/hyperledger/besu/RunnerBuilder.java
  besu/src/main/java/org/hyperledger/besu/cli/BesuCommand.java
  besu/src/main/java/org/hyperledger/besu/cli/options/NatOptions.java
  besu/src/test/java/org/hyperledger/besu/cli/CommandTestAbstract.java
  besu/src/test/java/org/hyperledger/besu/cli/NatOptionsTest.java
  besu/src/test/resources/everything_config.toml
  nat/build.gradle
  nat/src/main/java/org/hyperledger/besu/nat/NatMethod.java
  nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesDetector.java
  nat/src/main/java/org/hyperledger/besu/nat/kubernetes/KubernetesNatManager.java
  nat/src/main/java/org/hyperledger/besu/nat/kubernetes/service/KubernetesServiceType.java
  nat/src/main/java/org/hyperledger/besu/nat/kubernetes/service/LoadBalancerBasedDetector.java
  nat/src/test/java/org/hyperledger/besu/nat/kubernetes/KubernetesClusterIpNatManagerTest.java
  nat/src/test/java/org/hyperledger/besu/nat/kubernetes/KubernetesLoadManagerNatManagerTest.java
  nat/src/test/java/org/hyperledger/besu/nat/kubernetes/KubernetesUnknownNatManagerTest.java
  platform/build.gradle
Labels: doc-change-required, breaking

#8300 Don't access state before OOG check for contract account proof of abs…
  evm/src/main/java/org/hyperledger/besu/evm/processor/ContractCreationProcessor.java
Labels: verkle

#8295 [build] update use of gradle deprecated features
  build.gradle
  ethereum/evmtool/build.gradle
  ethereum/referencetests/build.gradle
Labels: dev experience

#8341 disable on mac: PendingTransactionEstimatedMemorySizeTest
  ethereum/eth/src/test/java/org/hyperledger/besu/ethereum/eth/transactions/PendingTransactionEstimatedMemorySizeTest.java
Labels: testing

#8322 Implement reverting of witnesses in case of OOG
  datatypes/src/main/java/org/hyperledger/besu/datatypes/AccessEvent.java
  datatypes/src/main/java/org/hyperledger/besu/datatypes/AccessWitness.java
  ethereum/core/src/main/java/org/hyperledger/besu/ethereum/vm/Eip7709BlockHashLookup.java
  ethereum/core/src/test/java/org/hyperledger/besu/ethereum/vm/Eip7709BlockHashLookupTest.java
  evm/src/main/java/org/hyperledger/besu/evm/EVM.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/Eip4762GasCalculator.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/AccessEvents.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/BranchAccessEvent.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/Eip4762AccessWitness.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/LeafAccessEvent.java
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/stateless/NoopAccessWitness.java
  evm/src/main/java/org/hyperledger/besu/evm/operation/SLoadOperation.java
  evm/src/test/java/org/hyperledger/besu/evm/gascalculator/stateless/Eip4762AccessWitnessTest.java
Labels: verkle
