Repository hyperledger/besu, pull requests merged in 2025-06, with the labels that each got.

#8738 chore: increase default gas cap to 100M
  ethereum/api/src/main/java/org/hyperledger/besu/ethereum/api/ApiConfiguration.java
  ethereum/api/src/test/resources/org/hyperledger/besu/ethereum/api/jsonrpc/eth/simulateV1/specs/eth_simulateV1-simple.json
Labels: doc-change-required

#8589 Change Maven artifactIds to avoid possible collisions with other libs
  CHANGELOG.md
  acceptance-tests/dsl/build.gradle
  besu/build.gradle
  build.gradle
  config/build.gradle
  consensus/clique/build.gradle
  consensus/common/build.gradle
  consensus/ibft/build.gradle
  consensus/ibftlegacy/build.gradle
  consensus/merge/build.gradle
  consensus/qbft-core/build.gradle
  consensus/qbft/build.gradle
  crypto/algorithms/build.gradle
  crypto/services/build.gradle
  datatypes/build.gradle
  ethereum/api/build.gradle
  ethereum/blockcreation/build.gradle
  ethereum/core/build.gradle
  ethereum/eth/build.gradle
  ethereum/ethstats/build.gradle
  ethereum/evmtool/build.gradle
  ethereum/mock-p2p/build.gradle
  ethereum/p2p/build.gradle
  ethereum/permissioning/build.gradle
  ethereum/referencetests/build.gradle
  ethereum/rlp/build.gradle
  ethereum/stratum/build.gradle
  ethereum/trie/build.gradle
  ethereum/verkletrie/build.gradle
  evm/build.gradle
  metrics/core/build.gradle
  metrics/rocksdb/build.gradle
  nat/build.gradle
  platform/build.gradle
  plugin-api/build.gradle
  plugins/rocksdb/build.gradle
  services/kvstore/build.gradle
  services/pipeline/build.gradle
  services/tasks/build.gradle
  testfuzz/build.gradle
  testutil/build.gradle
  util/build.gradle
Labels: breaking

#8768 feat: move pay opcode to future eips
  ethereum/evmtool/src/test/resources/org/hyperledger/besu/evmtool/state-test/pay-opcode.json
  evm/src/main/java/org/hyperledger/besu/evm/MainnetEVMs.java
Labels: Osaka

#8766 EIP-7883: adjust modexp gas computation
  evm/src/main/java/org/hyperledger/besu/evm/gascalculator/OsakaGasCalculator.java
Labels: Osaka

#8811 Improve extcodehash perf
  evm/src/main/java/org/hyperledger/besu/evm/operation/ExtCodeHashOperation.java
Labels: performance
